functionsDirectory = "C:\\Users\\snipe\\OneDrive\\Documents\\business_docs\\hfts\\hfts_website\\hfts_repo\\project-bolt-sb1-z4q8pfh7\\happy_fun_time_snacks\\frontend\\netlify\\functions"
functionsDirectoryOrigin = "config"
redirectsOrigin = "config"
headers = []

[build]
publish = "C:\\Users\\snipe\\OneDrive\\Documents\\business_docs\\hfts\\hfts_website\\hfts_repo\\project-bolt-sb1-z4q8pfh7\\happy_fun_time_snacks\\frontend\\dist"
publishOrigin = "config"
commandOrigin = "config"
command = "npm run build"
base = "C:\\Users\\snipe\\OneDrive\\Documents\\business_docs\\hfts\\hfts_website\\hfts_repo\\project-bolt-sb1-z4q8pfh7\\happy_fun_time_snacks\\frontend"
functions = "C:\\Users\\snipe\\OneDrive\\Documents\\business_docs\\hfts\\hfts_website\\hfts_repo\\project-bolt-sb1-z4q8pfh7\\happy_fun_time_snacks\\frontend\\netlify\\functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[dev]
framework = "vite"
targetPort = 5173.0
port = 8888.0

[functions]

[functions."*"]
node_bundler = "esbuild"

[[plugins]]
origin = "config"
package = "@netlify/plugin-functions-install-core"

[plugins.inputs]

[[redirects]]
from = "https://profound-figolla-72e059.netlify.app/*"
to = "https://www.happyfuntimesnacks.com/:splat"
status = 301.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/sitemap.xml"
to = "/sitemap.xml"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]